server:
  port: 10081
spring:
  application:
    name: post-server
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ang?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: cape
  redis:
    host: 192.168.23.129
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10023/eureka/
    #      defaultZone: http://192.168.9.12:11010/eureka/
    instance:
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 20
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}

mybatis-plus:
  #type-aliases-package: com.mc.postserver.entity # 别名扫描包
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type: ASSIGN_ID
logging:
  level:
    com.hmdp: debug